Ecommerce-Django/src/api/urls.py
from django.urls import path, include 

urlpatterns = [

    path('admin/',admin.site.urls)
    path('',include(products.urls))
    
]



from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

class ExampleView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, format=None):
        content = {
            'status': 'request was permitted'
        }
        return Response(content)

Ecommerce-Django/src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LogoutView
from .views import home_page, about_page, contact_page, login_page, register_page
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^register/$', register_page, name='register'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^admin/', admin.site.urls),
    # url('', include('products.urls')), # for rest api
    url(r'^auth/', include('social_django.urls', namespace='social')), # Using  Social django urls for google signin
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce-Django/src/products/urls.py
from django.conf.urls import url

from django.conf.urls import  include
from . import views 
from rest_framework import routers 
router = routers.DefaultRouter ()
router.register('products',views.productsview)

from .views import (
        ProductListView, 
        ProductDetailSlugView, 
        )

urlpatterns = [

    url(r'^restapi/',include((router.urls), namespace='rest' )),
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

Ecommerce-Django/src/templates/base/css.html
{% load static %}

<link rel='stylesheet' href='{% static "css/main.css" %}' >

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">


<!-- Fontawesome CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

Ecommerce-Django/src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

Ecommerce-Django/src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
   <div class='container'>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_list_url }}">Products</a>
      </li>

      {% if request.user.is_authenticated %}
       <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{ logout_url }}">Logout</a>
      </li>
      {% else %}
       <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>

      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"> {{ request.session.cart_items }} <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>
    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</div>
</nav>