Ecommerce-Django/src/api/urls.py
from django.urls import path, include 

urlpatterns = [

    path('admin/',admin.site.urls)
    path('',include(products.urls))
    
]



from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

class ExampleView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, format=None):
        content = {
            'status': 'request was permitted'
        }
        return Response(content)

Ecommerce-Django/src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LogoutView
from .views import home_page, about_page, contact_page, login_page, register_page
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^register/$', register_page, name='register'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^admin/', admin.site.urls),
    # url('', include('products.urls')), # for rest api
    url(r'^auth/', include('social_django.urls', namespace='social')), # Using  Social django urls for google signin
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce-Django/src/search/urls.py
from django.conf.urls import url

from .views import (
        SearchProductView
        )

urlpatterns = [
    url(r'^$', SearchProductView.as_view(), name='query'),
]

Ecommerce-Django/src/search/models.py
from django.db import models

# Create your models here.

Ecommerce-Django/src/search/views.py
from django.shortcuts import render
from django.views.generic import ListView
from products.models import Product
from itertools import chain


class SearchProductView(ListView):
    template_name = "search/view.html"

    def get_context_data(self, *args, **kwargs):
        context = super(SearchProductView, self).get_context_data(*args, **kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        method_dict = request.GET
        query = method_dict.get('q', None)
        # Here we are spliting the searched string after comma 
        # and saving them in a list
        queryList = query.split(', ')
        object_list = []
        for query in queryList:
            # and here we are looping through that list one by one 
            # and looking up the query for that object in database
            # the search function returning an queryset
            # and we are merging all the list to an signle list
            object_list = chain(object_list,Product.objects.search(query))
        return object_list
        

Ecommerce-Django/src/search/templates/search/snippets/search-form.html
<form id="labnol" method='GET' action='{% url "search:query" %}' class="form my-2 my-lg-0 search-form">
  <div class='input-group'>
    <input id="transcript" class="form-control" type="text" placeholder="Search" name='q' aria-label="Search"'>
    <i onclick="startDictation()" class="fa fa-microphone" style="font-size:24px; padding: 5px 0 0 10px;"></i>
    </div>
</form>

<!-- We are implemnting voice search using The new JavaScript Web Speech API
 The Dictation App also uses the speech recognition API though it writes the transcribed text to textarea field instead of an input box. -->
<script>
      function startDictation() {

        if (window.hasOwnProperty('webkitSpeechRecognition')) {

          var recognition = new webkitSpeechRecognition();

          recognition.continuous = false;
          recognition.interimResults = false;

          recognition.lang = "en-US";
          recognition.start();

          recognition.onresult = function(e) {
            document.getElementById('transcript').value
                                     = e.results[0][0].transcript;
            recognition.stop();
            document.getElementById('labnol').submit();
          };

          recognition.onerror = function(e) {
            recognition.stop();
          }

        }
      }
  </script>